#!/bin/bash
# See https://github.com/dreeves/scrumbs
# Open crumbudget.html with the real numbers: the bands from scrumbs.conf and
# the per-moment sizes and slot occupancy measured off the screenshots on disk.
# The page can't gather any of that itself -- a file:// page may not read
# scrumbs.conf, let alone stat a directory -- so this writes the measurements
# to crumbudget.data.js beside the html, the one thing a file:// page *can*
# load (a same-directory script tag). Not a url fragment: macOS `open` strips
# #fragments and ?queries from file:// urls before the browser sees them.

set -euo pipefail

srcdir=$(cd "$(dirname "$0")" && pwd)
. "$srcdir/scrumblib.sh"
. "${SCRUMBSCONF:-$srcdir/scrumbs.conf}"  # path & bands live in scrumbs.conf

bandsparse "$bands"
[[ -d $path ]]           || die "no such directory: $path"
[[ $srcdir != *" "* ]]   || die "spaces in the path to crumbudget.html: $srcdir"

tmpd=$(mktemp -d)
trap 'rm -rf "$tmpd"' EXIT

# "name size" for every screenshot. xargs because a glob over a year of
# captures blows past the command-line length limit.
(cd "$path" && find . -maxdepth 1 -type f \( -name '*.jpg' -o -name '*.webp' \) \
  -print0 | xargs -0 stat -f '%N %z' | sed 's|^\./||') > "$tmpd/sz"
# No mid-measurement race guard is needed: a file swept away between find
# and stat fails the collection pipeline itself under set -euo pipefail, and
# an unparseable name kills name2epoch -- both die loudly on their own.
cut -d' ' -f1 "$tmpd/sz" | name2epoch > "$tmpd/ep"
# name2epoch is a straight awk filter, so ep and sz stay in lockstep and paste
# can zip them by position into the "epoch name size" lines crumbstat wants.
# One localnow serves both aggregations below, so the moments' ages and the
# scalars' span come from the same instant and the page's cross-checks hold.
now=$(localnow)
paste -d' ' <(cut -d' ' -f1 "$tmpd/ep") "$tmpd/sz" > "$tmpd/epsz"
crumbstat "$now" "$edges" "$pers" < "$tmpd/epsz" > "$tmpd/stat"
read -r jpgb webpb occup span rawmom arcmom < "$tmpd/stat"
momsjs=$(crumbmoms "$now" < "$tmpd/epsz" | \
         awk '{ printf "    [%s, %s, %s],\n", $1, $2, $3 }')

cat > "$srcdir/crumbudget.data.js" <<EOF
// Generated by crumbudget.sh; loaded by crumbudget.html. Rerun ./crumbudget.sh
// to remeasure -- don't edit or commit this file.
const CRUMBDATA = {
  bands: "$bands",
  jpgb: $jpgb, webpb: $webpb, occup: $occup,
  span: $span, rawmom: $rawmom, arcmom: $arcmom,
  moms: [  // one [agesec, jpgbytes, webpbytes] per moment, ages ascending
$momsjs
  ],
};
EOF
echo "wrote $srcdir/crumbudget.data.js"
open "file://$srcdir/crumbudget.html"
